// Run once after installing minecraft-data:
//   npm install minecraft-data
//   node scripts/generateMinecraftData.mjs
//
// This generates browser-friendly static data so the React app does not
// need to import the Node-only minecraft-data package at runtime.

import fs from 'node:fs';
import path from 'node:path';
import minecraftData from 'minecraft-data';

const VERSION = '26.1';
const mcData = minecraftData(VERSION);

const outputDir = path.resolve('src/data');
fs.mkdirSync(outputDir, { recursive: true });

const items = mcData.itemsArray
  .filter((item) => item && item.id != null && item.name)
  .map((item) => ({
    id: item.id,
    name: item.name,
    displayName: item.displayName || item.name,
    stackSize: item.stackSize || 64,
  }))
  .sort((a, b) => a.displayName.localeCompare(b.displayName));

function itemId(value) {
  if (value == null) return null;

  if (typeof value === 'number') return value;

  if (Array.isArray(value)) {
    return typeof value[0] === 'number' ? value[0] : null;
  }

  if (typeof value === 'object' && typeof value.id === 'number') {
    return value.id;
  }

  return null;
}

function flattenShape(shape) {
  if (!Array.isArray(shape)) return [];
  return shape.flatMap((row) => (Array.isArray(row) ? row : [row]));
}

function ingredientIds(recipe) {
  if (Array.isArray(recipe.ingredients)) {
    return recipe.ingredients
      .map(itemId)
      .filter((id) => id != null);
  }

  if (Array.isArray(recipe.inShape)) {
    return flattenShape(recipe.inShape)
      .map(itemId)
      .filter((id) => id != null);
  }

  return [];
}

function resultInfo(recipe, fallbackId) {
  const result = recipe?.result;

  if (typeof result === 'number') {
    return { id: result, count: 1 };
  }

  if (result && typeof result === 'object' && typeof result.id === 'number') {
    return {
      id: result.id,
      count: Number.isFinite(result.count) && result.count > 0
        ? result.count
        : 1,
    };
  }

  return { id: fallbackId, count: 1 };
}

const itemById = new Map(items.map((item) => [item.id, item]));

const recipes = [];

for (const [idString, recipeList] of Object.entries(mcData.recipes || {})) {
  const fallbackId = Number(idString);
  if (!Array.isArray(recipeList)) continue;

  for (let index = 0; index < recipeList.length; index += 1) {
    const rawRecipe = recipeList[index];
    const result = resultInfo(rawRecipe, fallbackId);

    if (!result.id || !itemById.has(result.id)) continue;

    const ids = ingredientIds(rawRecipe);
    if (!ids.length) continue;

    const counts = new Map();

    for (const id of ids) {
      counts.set(id, (counts.get(id) || 0) + 1);
    }

    const ingredients = [...counts.entries()]
      .map(([ingredientId, count]) => {
        const item = itemById.get(ingredientId);
        if (!item) return null;

        return {
          id: item.id,
          name: item.name,
          displayName: item.displayName,
          stackSize: item.stackSize,
          count,
        };
      })
      .filter(Boolean)
      .sort((a, b) => a.displayName.localeCompare(b.displayName));

    if (!ingredients.length) continue;

    recipes.push({
      id: `${result.id}-${index}`,
      outputId: result.id,
      outputCount: result.count,
      ingredients,
    });
  }
}

recipes.sort(
  (a, b) =>
    a.outputId - b.outputId ||
    a.id.localeCompare(b.id)
);

const file = `// AUTO-GENERATED by scripts/generateMinecraftData.mjs\n// Minecraft Java Edition ${VERSION}\n// Do not edit manually.\n\nexport interface MinecraftItem {\n  id: number;\n  name: string;\n  displayName: string;\n  stackSize: number;\n}\n\nexport interface MinecraftIngredient {\n  id: number;\n  name: string;\n  displayName: string;\n  stackSize: number;\n  count: number;\n}\n\nexport interface MinecraftRecipe {\n  id: string;\n  outputId: number;\n  outputCount: number;\n  ingredients: MinecraftIngredient[];\n}\n\nexport const MINECRAFT_ITEMS: MinecraftItem[] = ${JSON.stringify(items, null, 2)};\n\nexport const MINECRAFT_RECIPES: MinecraftRecipe[] = ${JSON.stringify(recipes, null, 2)};\n`;

fs.writeFileSync(
  path.join(outputDir, 'minecraftData.ts'),
  file,
  'utf8'
);

console.log(`Generated ${items.length} items and ${recipes.length} recipes for Minecraft Java ${VERSION}.`);
